<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Member;

class MemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            [
                'senior_citizen_id_no' => 'SC2024-000001',
                'first_name' => 'Juan',
                'last_name' => 'Dela Cruz',
                'date_of_birth' => '1950-01-15',
                'gender' => 'Male',
                'brgy' => 'Balinad',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '123 Barangay Road',
                'phone_number' => '09123456789',
                'email' => 'juan.delacruz@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000002',
                'first_name' => 'Maria',
                'last_name' => 'Santos',
                'date_of_birth' => '1955-05-25',
                'gender' => 'Female',
                'brgy' => 'Centro Oriental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '456 Poblacion Street',
                'phone_number' => '09198765432',
                'email' => 'maria.santos@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000003',
                'first_name' => 'Jose',
                'last_name' => 'Reyes',
                'date_of_birth' => '1952-03-12',
                'gender' => 'Male',
                'brgy' => 'Tagaytay',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '789 Tagaytay Street',
                'phone_number' => '09171234567',
                'email' => 'jose.reyes@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000004',
                'first_name' => 'Rosa',
                'last_name' => 'Flores',
                'date_of_birth' => '1954-06-08',
                'gender' => 'Female',
                'brgy' => 'Napo',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '321 Napo Road',
                'phone_number' => '09182345678',
                'email' => 'rosa.flores@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000005',
                'first_name' => 'Andres',
                'last_name' => 'Ramos',
                'date_of_birth' => '1949-11-18',
                'gender' => 'Male',
                'brgy' => 'Centro Occidental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '654 Poblacion Street',
                'phone_number' => '09193456789',
                'email' => 'andres.ramos@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000006',
                'first_name' => 'Luz',
                'last_name' => 'Garcia',
                'date_of_birth' => '1951-09-22',
                'gender' => 'Female',
                'brgy' => 'San Vicente Sur',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '12 Vicente Road',
                'phone_number' => '09202345678',
                'email' => 'luz.garcia@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000007',
                'first_name' => 'Ricardo',
                'last_name' => 'Torres',
                'date_of_birth' => '1953-05-14',
                'gender' => 'Male',
                'brgy' => 'Santa Cruz',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '45 Cruz Avenue',
                'phone_number' => '09213456789',
                'email' => 'ricardo.torres@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000008',
                'first_name' => 'Ana',
                'last_name' => 'Navarro',
                'date_of_birth' => '1956-02-09',
                'gender' => 'Female',
                'brgy' => 'Ponson',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '76 Ponson Lane',
                'phone_number' => '09224567890',
                'email' => 'ana.navarro@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000009',
                'first_name' => 'Roberto',
                'last_name' => 'Aquino',
                'date_of_birth' => '1957-12-05',
                'gender' => 'Male',
                'brgy' => 'Balinad',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '98 Balinad Boulevard',
                'phone_number' => '09235678901',
                'email' => 'roberto.aquino@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000010',
                'first_name' => 'Carla',
                'last_name' => 'Rivera',
                'date_of_birth' => '1958-07-16',
                'gender' => 'Female',
                'brgy' => 'Iraya Norte',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '43 Iraya Norte Street',
                'phone_number' => '09246789012',
                'email' => 'carla.rivera@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000011',
                'first_name' => 'Miguel',
                'last_name' => 'Fernandez',
                'date_of_birth' => '1952-11-23',
                'gender' => 'Male',
                'brgy' => 'Danao',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '102 Danao Street',
                'phone_number' => '09257890123',
                'email' => 'miguel.fernandez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000012',
                'first_name' => 'Teresa',
                'last_name' => 'Diaz',
                'date_of_birth' => '1950-04-02',
                'gender' => 'Female',
                'brgy' => 'Basud',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '100 Basud Road',
                'phone_number' => '09268901234',
                'email' => 'teresa.diaz@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000013',
                'first_name' => 'Ramon',
                'last_name' => 'Bautista',
                'date_of_birth' => '1949-08-15',
                'gender' => 'Male',
                'brgy' => 'Kinale',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '75 Kinale Drive',
                'phone_number' => '09279012345',
                'email' => 'ramon.bautista@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000014',
                'first_name' => 'Nena',
                'last_name' => 'Villar',
                'date_of_birth' => '1955-10-10',
                'gender' => 'Female',
                'brgy' => 'Centro Occidental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '89 Poblacion Road',
                'phone_number' => '09280123456',
                'email' => 'nena.villar@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000015',
                'first_name' => 'Pedro',
                'last_name' => 'Castro',
                'date_of_birth' => '1953-12-12',
                'gender' => 'Male',
                'brgy' => 'San Antonio',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '34 Antonio Street',
                'phone_number' => '09291234567',
                'email' => 'pedro.castro@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000016',
                'first_name' => 'Elena',
                'last_name' => 'Mendoza',
                'date_of_birth' => '1954-11-01',
                'gender' => 'Female',
                'brgy' => 'La Medalla',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '77 Medalla Avenue',
                'phone_number' => '09301234567',
                'email' => 'elena.mendoza@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000017',
                'first_name' => 'Felipe',
                'last_name' => 'Delos Santos',
                'date_of_birth' => '1952-06-24',
                'gender' => 'Male',
                'brgy' => 'Tula-Tula',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '21 Tula Street',
                'phone_number' => '09312345678',
                'email' => 'felipe.delossantos@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000018',
                'first_name' => 'Lilia',
                'last_name' => 'Ortega',
                'date_of_birth' => '1957-04-06',
                'gender' => 'Female',
                'brgy' => 'Balinad',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '99 Balinad Street',
                'phone_number' => '09323456789',
                'email' => 'lilia.ortega@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000019',
                'first_name' => 'Jesus',
                'last_name' => 'Magbanua',
                'date_of_birth' => '1958-09-30',
                'gender' => 'Male',
                'brgy' => 'Tuburan',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '84 Tuburan Road',
                'phone_number' => '09334567890',
                'email' => 'jesus.magbanua@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000020',
                'first_name' => 'Carmen',
                'last_name' => 'Cruz',
                'date_of_birth' => '1951-01-25',
                'gender' => 'Female',
                'brgy' => 'Centro Occidental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '56 Poblacion Road',
                'phone_number' => '09345678901',
                'email' => 'carmen.cruz@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000021',
                'first_name' => 'Esteban',
                'last_name' => 'Villanueva',
                'date_of_birth' => '1949-03-17',
                'gender' => 'Male',
                'brgy' => 'San Vicente Norte',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '16 Vicente Street',
                'phone_number' => '09356789012',
                'email' => 'esteban.villanueva@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000022',
                'first_name' => 'Guadalupe',
                'last_name' => 'Martinez',
                'date_of_birth' => '1955-07-29',
                'gender' => 'Female',
                'brgy' => 'Centro Oriental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '12 Poblacion Avenue',
                'phone_number' => '09367890123',
                'email' => 'guadalupe.martinez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000023',
                'first_name' => 'Manuel',
                'last_name' => 'Guzman',
                'date_of_birth' => '1950-12-19',
                'gender' => 'Male',
                'brgy' => 'Santa Cruz',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '47 Cruz Avenue',
                'phone_number' => '09378901234',
                'email' => 'manuel.guzman@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000024',
                'first_name' => 'Victoria',
                'last_name' => 'Bermudez',
                'date_of_birth' => '1953-05-27',
                'gender' => 'Female',
                'brgy' => 'San Jose',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '62 Jose Road',
                'phone_number' => '09389012345',
                'email' => 'victoria.bermudez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000025',
                'first_name' => 'Amado',
                'last_name' => 'Sarmiento',
                'date_of_birth' => '1951-11-11',
                'gender' => 'Male',
                'brgy' => 'Centro Occidental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '102 Poblacion Street',
                'phone_number' => '09390123456',
                'email' => 'amado.sarmiento@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000026',
                'first_name' => 'Esperanza',
                'last_name' => 'Lopez',
                'date_of_birth' => '1954-08-18',
                'gender' => 'Female',
                'brgy' => 'San Miguel',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '65 Miguel Lane',
                'phone_number' => '09401234567',
                'email' => 'esperanza.lopez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000027',
                'first_name' => 'Gregorio',
                'last_name' => 'Perez',
                'date_of_birth' => '1952-04-30',
                'gender' => 'Male',
                'brgy' => 'Balinad',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '72 Balinad Boulevard',
                'phone_number' => '09412345678',
                'email' => 'gregorio.perez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000028',
                'first_name' => 'Isabel',
                'last_name' => 'Mendoza',
                'date_of_birth' => '1951-03-02',
                'gender' => 'Female',
                'brgy' => 'San Roque',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '83 Roque Avenue',
                'phone_number' => '09423456789',
                'email' => 'isabel.mendoza@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000029',
                'first_name' => 'Alfonso',
                'last_name' => 'Gonzalez',
                'date_of_birth' => '1950-06-15',
                'gender' => 'Male',
                'brgy' => 'Napo',
                'city' => 'Polangui',
                'province' => 'Albay',
                'postal_code' => '4506',
                'text_address' => '21 Napo Road',
                'phone_number' => '09434567890',
                'email' => 'alfonso.gonzalez@example.com',
            ],
            [
                'senior_citizen_id_no' => 'SC2024-000030',
                'first_name' => 'Mercedes',
                'last_name' => 'Villareal',
                'date_of_birth' => '1956-01-19',
                'gender' => 'Female',
                'brgy' => 'Centro Oriental (Poblacion)',
                'city' => 'Oas',
                'province' => 'Albay',
                'postal_code' => '4504',
                'text_address' => '35 Poblacion Lane',
                'phone_number' => '09445678901',
                'email' => 'mercedes.villareal@example.com',
            ],
        ];

        foreach ($members as $member) {
            Member::create($member);
        }
    }
}
